# Generated by Django 3.1.4 on 2021-02-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocationapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='total_v',
            field=models.IntegerField(default=30),
        ),
    ]
